<?php
$data = $this->reportData;
$header = $data['header'];
$global = $data['global'];
$tasks = $data['tasks'];
$ips = implode(" ", $header['ip']);
$date = date("H:i:s d/m/Y");
$color = $global['completed'] == $global['total'] ? "green" : "red";
$message = <<<MESSAGE
<html>
<head>
</head>
<body>
<center>
    <br />
    <br />
    <p><b><span style='color: #660000;'>{$header['hostname']} ({$ips})</span></b></p>
    <p><b><span style='color: #660000;'>Статиcтика {{$date}}</span></b></p>
    <p><b><span style='color: #660000;'>Uptime {$header['uptime']}</span></b></p>
    <p><b>
            <span style='color: {$color};'>Выполнено {$global['completed']} из {$global['total']} задач.</span>
        </b></p>
</center>
<table border='1' cellspacing='0'
       cellpadding='0' width='100%' style='width: 100.0%; border-collapse: collapse; border: none;'>
    <thead>
    <tr style='height: 25px;'>
        <th style='text-align: center;'>№</th>
        <th style='text-align: center;'>Name</th>
        <th style='text-align: center;'>Start time</th>
        <th style='text-align: center;'>End time</th>
        <th style='text-align: center;'>Performed</th>
        <th style='text-align: center;'>Total</th>
        <th style='text-align: center;'>Complited</th>
        <th style='text-align: center;'>Status</th>
    </tr>
    </thead>
    <tbody>
MESSAGE;

$i = 1;
foreach ($tasks as $task) {
    $performed = $this->showPeriod($task['mend'] - $task['mstart']);
    $background = $task['total'] != $task['completed'] ? " background:red; color: white;" : "";
    $status = $task['total'] == $task['completed'] ? "OK" : "<b>ERROR</b>";
    $message .= <<<MESSAGE
    <tr style='height: 25px;'>
        <td style='text-align: center;'>{$i}</td>
        <td style='text-align: center;'>{$task['name']}</td>
        <td style='text-align: center;'>{$task['start']}</td>
        <td style='text-align: center;'>{$task['end']}</td>
        <td style='text-align: center;'>{$performed}</td>
        <td style='text-align: center;'>{$task['total']}</td>
        <td style='text-align: center;'>{$task['completed']}</td>
        <td style='text-align: center;{$background}'>{$status}</td>
    </tr>
MESSAGE;
    $i++;
}

$message .= <<<MESSAGE
    </tbody>
</table>
MESSAGE;

foreach ($tasks as $task) {
    $background = $task['total'] == $task['completed'] ? " background: silver;" : " background: red;";
    $message .= <<<MESSAGE
<br />
<br />
<table border='1' cellspacing='0' cellpadding='0' width='100%'
       style='width: 100.0%; border-collapse: collapse; border: none;'>
    <thead>
    <caption style='line-height:25px; color: white; {$background}>
                        <b>task: \"{$task['name']}\" ({$task['completed']}completed commands of {$task['total']})<b>
        </caption>
        <tr style='height: 25px;'>
            <th style='text-align: center;'>№</th>
            <th style='text-align: center;'>Name</th>
            <th style='text-align: center;'>Start time</th>
            <th style='text-align: center;'>End time</th>
            <th style='text-align: center;'>Performed</th>
            <th style='text-align: center;'>Return</th>
            <th style='text-align: center;'>Status</th>
        </tr>
    </thead>
    <tbody>
MESSAGE;
    $i = 1;
    foreach ($task['commands'] as $command) {
        if ($command['status'] == 1 && $command['hide'] == true) {
            $i++;
            continue;
        } else {
            $performed = $this->showPeriod($command['mend'] - $command['mstart']);
            $return = isset($command['return']) ? $command['return'] : "";
            $background = $command['status'] ? "" : " background:red; color: white;";
            $status = $command['status'] ? "OK" : "<b>ERROR</b>";
            $message .= <<<MESSAGE
    <tr style='height: 25px;'>\n";
        <td style='text-align: center;'>{$i}</td>
        <td style='text-align: center;'>{$command['name']}</td>
        <td style='text-align: center;'>{$command['start']}</td>
        <td style='text-align: center;'>{$command['end']}</td>
        <td style='text-align: center;'>{$performed}</td>
        <td style='text-align: center;'>{$return}</td>
        <td style='text-align: center;{$background}'>{$status}</td>
    </tr>
MESSAGE;
            $i++;
        }
    }
    if (!empty($task['commandList'])) {
        foreach ($task['commandList'] as $command) {
            $message .= <<<MESSAGE
    <tr style='height: 25px;'>
        <td style='text-align: center;'>{$i}</td>
        <td style='text-align: center;'>{$command[0]}</td>
        <td style='text-align: center;'></td>
        <td style='text-align: center;'></td>
        <td style='text-align: center;'></td>
        <td style='text-align: center;'></td>
        <td style='text-align: center; background:red; color: white;'><b>ERROR</b></td>
    </tr>\n";
MESSAGE;
            $i++;
        }
    }
    $message .= <<<MESSAGE
    </tbody>
</table>
<br />
<br />
MESSAGE;
}
$message .= <<<MESSAGE
</body>
</html>
MESSAGE;